services:
  surrealdb:
    container_name: vertex-surrealdb
    hostname: surrealdb
    build:
      context: .
      dockerfile: ./surrealdb.Dockerfile
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - surrealdb-data:/data

  backend:
    container_name: vertex-server
    hostname: backend
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - surrealdb
    ports:
      - "3000:3000"

volumes:
  surrealdb-data: